### ISSUE TITLE
NameError: name 'fd' is not defined

### ISSUE THREAD

**Issue by DarioPanada** [SyntaxVoid/py_menu#2]
The following occur:

```
Traceback (most recent call last):
  File "/home/dario/py_menu/py_menu/examples/broken_example.py", line 13, in <module>
    main_menu.mainloop()
  File "/home/dario/py_menu/py_menu/__init__.py", line 236, in mainloop
    any_key_to_continue()
  File "/home/dario/py_menu/py_menu/__init__.py", line 110, in any_key_to_continue
    getch()
  File "/home/dario/py_menu/py_menu/__init__.py", line 20, in getch
    old_attr = termios.tcgetattr(fd)
NameError: name 'fd' is not defined
```

When trying to run:

```
from py_menu import Menu, Option

def sayHi():
    print("hi")
    return

if __name__ == "__main__":
    main_menu = Menu(header = "Pick an option",
                     splash = "Hello")

    main_menu.add_option("Say Hi", lambda: sayHi())

    main_menu.mainloop()
```

**Comment by SyntaxVoid** [comment]
Thanks for bringing this up. The `fd` variable causing the name error should actually be `file_desc`. If you wanted to make a pull request changing `fd` to `file_desc`, I would be happy to accept -- otherwise, I will make the change by tomorrow

**Comment by DarioPanada** [comment]
Like so? https://github.com/SyntaxVoid/py_menu/pull/4

**Comment by SyntaxVoid** [comment]
Perfect. Merged and closing. Thank you!
